site_name: Terraform-dojo ドキュメント
site_description: Terraformプロジェクトのドキュメント
site_author: takeyamatakashi

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - ホーム: index.md
  - プロジェクト概要: overview.md
  - モジュール:
      - 概要: modules/index.md
  - 変数一覧: variables.md
  - デプロイ方法: deployment.md
